"""empty message

Revision ID: f7882232f9fb
Revises: ffdc0a98111c
Create Date: 2025-05-10 01:48:04.877941

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f7882232f9fb'
down_revision = 'ffdc0a98111c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('first_name', sa.String(length=30), nullable=False))
        batch_op.add_column(sa.Column('last_name', sa.String(length=30), nullable=False))
        batch_op.add_column(sa.Column('prefered_name', sa.String(length=30), nullable=True))
        batch_op.add_column(sa.Column('profile_img', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('about', sa.String(length=300), nullable=True))
        batch_op.add_column(sa.Column('phone', sa.String(length=14), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('phone')
        batch_op.drop_column('about')
        batch_op.drop_column('profile_img')
        batch_op.drop_column('prefered_name')
        batch_op.drop_column('last_name')
        batch_op.drop_column('first_name')

    # ### end Alembic commands ###
