"""empty message

Revision ID: 9cbe53bb2001
Revises:
Create Date: 2025-05-12 21:20:30.959051

"""

from alembic import op
import sqlalchemy as sa


import os

environment = os.getenv("FLASK_ENV")
SCHEMA = os.environ.get("SCHEMA")


# revision identifiers, used by Alembic.
revision = "9cbe53bb2001"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("username", sa.String(length=40), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("hashed_password", sa.String(length=255), nullable=False),
        sa.Column("first_name", sa.String(length=30), nullable=False),
        sa.Column("last_name", sa.String(length=30), nullable=False),
        sa.Column("prefered_name", sa.String(length=30)),
        sa.Column("profile_img", sa.String()),
        sa.Column("about", sa.String(length=300)),
        sa.Column("phone", sa.String(length=14)),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
        sa.UniqueConstraint("username"),
    )
    op.create_table(
        "servers",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=30), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("username"),
    )

    op.create_table(
        "channels",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=30), nullable=False),
        sa.Column("public", sa.Boolean(), nullable=False),
        sa.Column("server_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "channel_messages",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("body", sa.String(length=300), nullable=False),
        sa.Column("channel_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["channel_messages.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "channel_message_reactions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("channel_message_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["channel_messages.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "channel_message_images",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("img_url", sa.String(length=300), nullable=True),
        sa.Column("channel_message_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["channel_message_id"],
            ["channel_messages.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )

    if environment == "production":
        op.execute(f"ALTER TABLE users SET SCHEMA {SCHEMA};")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("channel_message_images")
    op.drop_table("channel_message_reactions")
    op.drop_table("channel_messages")
    op.drop_table("channels")
    op.drop_table("servers")
    op.drop_table("users")
    # ### end Alembic commands ###
