"""empty message

Revision ID: d871610f3be7
Revises: 6277b151b37c
Create Date: 2025-05-13 13:21:53.864437

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd871610f3be7'
down_revision = '6277b151b37c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('channel_message_images', schema=None) as batch_op:
        batch_op.add_column(sa.Column('channel_message_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint('channel_message_images_channel_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'channel_messages', ['channel_message_id'], ['id'])
        batch_op.drop_column('channel_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('channel_message_images', schema=None) as batch_op:
        batch_op.add_column(sa.Column('channel_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('channel_message_images_channel_id_fkey', 'channel_messages', ['channel_id'], ['id'])
        batch_op.drop_column('channel_message_id')

    # ### end Alembic commands ###
