"""empty message

Revision ID: 6277b151b37c
Revises: 9cbe53bb2001
Create Date: 2025-05-13 12:07:37.854258

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6277b151b37c'
down_revision = '9cbe53bb2001'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('channel_message_images', schema=None) as batch_op:
        batch_op.add_column(sa.Column('channel_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint('channel_message_images_user_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'channel_messages', ['channel_id'], ['id'])
        batch_op.drop_column('user_id')

    with op.batch_alter_table('channel_message_reactions', schema=None) as batch_op:
        batch_op.drop_constraint('channel_message_reactions_user_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'channel_messages', ['message_id'], ['id'])
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])

    with op.batch_alter_table('channel_messages', schema=None) as batch_op:
        batch_op.drop_constraint('channel_messages_user_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'channels', ['channel_id'], ['id'])
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])

    with op.batch_alter_table('channels', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'servers', ['server_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('channels', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('channel_messages', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('channel_messages_user_id_fkey', 'channel_messages', ['user_id'], ['id'])

    with op.batch_alter_table('channel_message_reactions', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('channel_message_reactions_user_id_fkey', 'channel_messages', ['user_id'], ['id'])

    with op.batch_alter_table('channel_message_images', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('channel_message_images_user_id_fkey', 'channel_messages', ['user_id'], ['id'])
        batch_op.drop_column('channel_id')

    # ### end Alembic commands ###
